# HTCondor submit file for processing circuits
container_image = docker://atharvavidwans/nature_pyscf:latest
universe = container

Executable = submit_exact_curve.sh

docker_pull_policy = always


Log = job.log
Output = ./output/job_output_$(Process).txt  # Relative path
Error = ./error/job_error_$(Process).txt      # Relative path

request_cpus = 10
request_memory = 15GB
# arguments = $(Process)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = exact_curve.py
request_disk = 30GB 

queue 1