# HTCondor submit file for processing circuits
container_image = docker://atharvavidwans/qiskit_algo:latest
universe = container

Executable = submit_run_algo.sh

docker_pull_policy = ifnotpresent

Log = job.log
Output = ./output/job_output_$(Process).txt  # Relative path
Error = ./error/job_error_$(Process).txt      # Relative path

request_cpus = 1
request_memory = 1GB
arguments = $(Process)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../all_str_A_Q/circuits, run_algo.py
request_disk = 5GB 

queue 15